---
- name: KRB-CLUSTER | Create dump file with all principals
  ansible.builtin.command: kdb5_util dump {{ krb_kdc_db_dump_path }}
  changed_when: false

- name: KRB-CLUSTER | Connect to slave servers # noqa no-changed-when
  ansible.builtin.command: >-
    kprop -f {{ krb_kdc_db_dump_path }}
    {{ hostvars[item]['ansible_fqdn'] }}
  with_inventory_hostnames: krb_replica
  register: __clustered
  when: false in check_clustered.values()
