---
- name: KRB-SLAVE | KDC configuration
  ansible.builtin.template:
    src: "{{ krb_kdc_conf_path | basename }}.j2"
    dest: "{{ krb_kdc_conf_path }}"
    mode: "0644"
  notify: RESTART SLAVE SERVER

- name: KRB-SLAVE | KDC ACL configuration
  ansible.builtin.template:
    src: "{{ krb_kadm5_acl_path | basename }}.j2"
    dest: "{{ krb_kadm5_acl_path }}"
    mode: "0644"
  notify: RESTART SLAVE SERVER

- name: KRB-SLAVE | KDC ACL configuration
  ansible.builtin.template:
    src: "{{ krb_kpropd_acl_path | basename }}.j2"
    dest: "{{ krb_kpropd_acl_path }}"
    mode: "0644"
  notify: RESTART SLAVE SERVER

- name: KRB-SLAVE | Client configuration
  ansible.builtin.template:
    src: "{{ krb_conf_path | basename }}.j2"
    dest: "{{ krb_conf_path }}"
    mode: "0644"

- name: KRB-SLAVE | Create initial Kerberos database
  ansible.builtin.command: kdb5_util -P {{ master_db_pass }} create -s
  args:
    creates: "{{ krb_kdc_db }}"
  no_log: true

- name: KRB-SLAVE | Start kerberos distribution center
  ansible.builtin.service:
    name: "{{ krb_kdc_service }}"
    state: started
    enabled: true

- name: KRB-SLAVE | Start kerberos admin server
  ansible.builtin.service:
    name: "{{ krb_kadmind_service }}"
    state: started
  when:
    krb_cluster_result.msg is defined or
    krb_cluster_result.content | b64decode |
      int != ansible_play_hosts_all | length

- name: KRB-SLAVE | Stop kerberos admin server
  ansible.builtin.service:
    name: "{{ krb_kadmind_service }}"
    state: stopped
    enabled: false

- name: KRB-SLAVE | Start slave kerberos distribution center update server
  ansible.builtin.service:
    name: "{{ krb_kpropd_service }}"
    state: started
    enabled: true

- name: KRB-SLAVE | Create principal for slave host
  ansible.builtin.command: >-
    kadmin -p {{ krb_kadmin_user }}/admin -w {{ krb_kadmin_pass }}
    -q "add_principal -randkey host/{{ ansible_fqdn }}"
  no_log: true
  when:
    krb_host_princ_result.msg is defined or
    krb_host_princ_result.content |
      b64decode != ansible_play_hosts_all | join(',')
  notify:
    - HOST PRINCIPAL FLAG
    - Creating Cluster Flag

- name: KRB-SLAVE | Add slave host principal to keytab
  ansible.builtin.command: >-
    kadmin -p {{ krb_kadmin_user }}/admin -w {{ krb_kadmin_pass }}
    -q "ktadd -randkey host/{{ ansible_fqdn }}@{{ krb_realm_name | upper() }}"
  no_log: true
  when:
    krb_host_princ_result.msg is defined or
    krb_host_princ_result.content |
      b64decode != ansible_play_hosts_all | join(',')
  notify:
    - HOST PRINCIPAL FLAG
    - CLUSTER FLAG
