---
- name: KRB-CHEK | Check the master group is exist
  delegate_to: localhost
  ansible.builtin.fail:
    msg: "Cannot use kerberos roles if there is 'krb_master'
          group are not exist or empty!"
  when: krb_master_group | length == 0

- name: KRB-CHEK | Check is server allready clustered
  ansible.builtin.stat:
    path: "{{ krb_conf_dir }}__clustered"
  register: __check_clustered

- name: KRB-CHEK | Check clustered status
  ansible.builtin.set_fact:
    check_clustered: "{{ dict(ansible_play_hosts_all | zip(ansible_play_hosts_all |
                          map('extract', hostvars, ['__check_clustered',
                          'stat', 'exists']) | list)) }}"
