---
- name: Converge
  hosts:
    # - all
    - krb_master
    - krb_replica
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Develope | Adding custom /etc/hosts
      ansible.builtin.blockinfile:
        dest: /etc/hosts
        block: |
          10.20.90.83 repo.srv.int.cldxapp.ru

    - name: "Include role" # noqa syntax-check[specific]
      ansible.builtin.include_role:
        name: "kerberos"
