---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  vars:
    molecule_playbook: destroy
  roles:
    - role: cloudx.molecule_create_destroy # noqa syntax-check[specific]
