---
driver:
  name: delegated
platforms:
  - name: molecule-krb-master
    groups: ["krb_master"]
  - name: molecule-krb-slave
    groups: ["krb_replica"]

provisioner:
  name: ansible
  playbooks:
    create: create.yml
    destroy: destroy.yml
  inventory:
    group_vars:
      all:
        molecule_image: ${MOLECULE_OPENSTACK_IMAGE}
        molecule_flavor: ${MOLECULE_OPENSTACK_FLAVOR}
        molecule_network: ${MOLECULE_OPENSTACK_NETWORK}
        molecule_fip_pool: ${MOLECULE_OPENSTACK_FIP_POOL}
        molecule_ssh_user: ${MOLECULE_OPENSTACK_SSH_USER}
        molecule_cidr: ${MOLECULE_OPENSTACK_CIDR}
        molecule_dns: ${MOLECULE_OPENSTACK_DNS}
verifier:
  name: testinfra
